version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["pytest"]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
