name: CI

on:
  pull_request:  # PR作成・更新時にもCIを走らせる
    branches: ["*"]  # ← 全ブランチでpush時に動く
  push:  # 通常のpush時にもCIを走らせる
    branches: [feature/*]  # または ["*"] で全ブランチ

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Compose (build)
        run: docker compose build --build-arg BUILDKIT_INLINE_CACHE=1


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 app tests

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Run tests with Docker Compose
        run: |
          docker compose up --abort-on-container-exit
            docker compose down
